<?php
$headTitle = $this->translate('Remove processor');
$this->headTitle($headTitle);
?>
<center><div class="title icon48 computer" ><?= $this->escapeHtml($headTitle); ?></div></center>
<div class="content">
    <p><?= $this->translate('Are you sure that you want to remove the processor of this computer?') ?></p>
    <form method="post" name="processor-form" id="processor-form">
        <button type="submit" name="delete" id="delete-yes" class="icon12 ok" value="Ok"><?= $this->translate('Yes') ?></button>
        <button type="submit" name="delete" id="delete-cancel" class="icon12 cancel" value="Cancel"><?= $this->translate('Cancel') ?></button>
    </form>
</div>
