<?php
$headTitle = $this->translate('Processors');
$this->headTitle($headTitle);
?>
<center><div class="title icon48 processor" ><?= $this->escapeHtml($headTitle); ?></div></center>
<div class="content">
    <a class="icon12 new" href="<?= $this->url('processor', ['action' => 'add']); ?>">
        <?= $this->translate('Add new processor') ?>
    </a>
    <table>
        <tr>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Description') ?></th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($processors as $processor) : ?>
            <tr>
                <td><?= $this->escapeHtml($processor->getName()) ?></td>
                <td><?= $this->escapeHtml($processor->getDescription()) ?></td>
                <td>
                    <a class="icon12 edit cell" href="<?=
                    $this->url(
                            'processor', ['action' => 'edit', 'id' => $processor->getId()]
                    )
                    ?>"><?= $this->translate('Edit') ?></a>
                    <a class="icon12 remove cell" href="<?=
                    $this->url(
                            'processor', ['action' => 'delete', 'id' => $processor->getId()]
                    )
                    ?>"><?= $this->translate('Remove') ?></a>
                </td>
            </tr>
<?php endforeach; ?>
    </table>
</div>